### ISSUE TITLE
Several basic Issues and complaints

### ISSUE THREAD

**Issue by d-schmidt** [akshaaatt/Google-IAP#1]
A lose, unsorted lists or problems and missed expectations:

* `DataWrappers.BillingResponse.responseCode` default code is Google's OK code (0) when it shouldn't be any of [Google's codes](https://developer.android.com/reference/com/android/billingclient/api/BillingClient.BillingResponseCode) for wrapper errors
* No constant error codes, for wrapper errors. I would have to look into your source to find `"Products not fetched"` to `String.equal()` with and to know I must call something else first and when to check the int code and when to test the String.
* Wrong errors: I can't call something else. `"Products not fetched"` means Billing is not available at all, failed to connect, the init SKUs are unknown, or `connect() query()` is simply not yet done.
* Missing subscription support is hidden: this will cause NPEs or fail silently on purchase attempts. There is no public `isSubSupported()` method.
* Hiding errors: `BILLING_UNAVAILABLE` and other connection errors should trigger `listener.onError()`
* Hiding errors: `iapClient.launchBillingFlow()` returned response is ignored, silently. I never get a callback if the flow doesn't start.
* NPE: calling `makePurchase()` with an unknown sku
* NPE: `getAllPurchases()`if client is not ready
* enabling autoAcknoledge will also autoConsume
* naming: `getAllPurchases()` doesn't return purchases, `inAppEventsListener?.onProductsPurchased(validPurchases)` will be called. It is more a query than a get.
* lost service connections are ignored or crash, `disconnected -> connect` is async so there might not currently be a connection
* no access to use backend server purchase validation
* it doesn't look robust: a lot of real fringe cases are ignored, like new or removed SKUs after app release and start. I expect my app not to crash for users if I add or remove an SKU in the Play Console.
* no helpful "hint" exceptions for programming errors.
  * i.e. `setSubscriptionIds()` could throw IllegalArgument if I use an empty list instead of telling me later querySku failed 
  * `iapClient.launchBillingFlow()` could tell me I never requested that SKU in `setSubscriptionIds()` instead of failing silently

**Comment by thubalek** [comment]
@d-schmidt  do you think it possible to fix them? I can contribute with pull requests but it would be nice to split those findings into separate issues and prioritize them.

**Comment by d-schmidt** [comment]
@akshaaatt did fix a few of them already and he is back to work after a two month break following my critique. I don't really care about this project, I just commented because he advertised it on reddit.

Feel free to create seperate issues for my bullet points after checking if they still apply.

**Comment by adrcotfas** [comment]
These are some good points.  @akshaaatt Do you need help to have these resolved?  Can you please create issues for what is left?

**Comment by akshaaatt** [comment]
@adrcotfas The list presented here was a bit long and I did not get the time to go through all of them sadly. I will work on this only after a week maybe. Until then if you want to go ahead with making the changes, please do so!

**Comment by ashutoshgngwr** [comment]
To add to @d-schmidt's list, the library doesn't address [handling purchases made outside your app](https://developer.android.com/google/play/billing/integrate#ooap).

**Comment by emzy07** [comment]
@d-schmidt Danke!

Your criticism is really justified I have addressed some points in a PR
