### ISSUE TITLE
Class file has wrong version 61.0, should be 55.0

### ISSUE THREAD

**Issue by jmimohsin** [akshaaatt/Google-IAP#118]
I am getting this issue with my Java project.

```
import com.limurse.iap.DataWrappers;
                      ^
  bad class file: C:\Users\Mohsin\.gradle\caches\transforms-3\85358dfce11a0fb70c376e431d155b1c\transformed\jetified-Google-IAP-1.4.2-api.jar(/com/limurse/iap/DataWrappers.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```
Same error is coming for IapConnector and PurchaseServiceListener.

**Comment by jmimohsin** [comment]
Update your Android Studio to latest one and Use JavaVersion.VERSION_17 as this SDK have.

**Comment by Oclemy** [comment]
Thanks. It works. For people checking this you have to perform those two steps.

**Comment by shreeguruprasad** [comment]
I'm also getting the same error. Where do I have to change the Java version?

**Comment by Oclemy** [comment]
1. You have to use the latest Android studio. It will come bundled with Java 17.
2. In your app/build.gradle under the buildTypes add:

```groovy
    buildTypes {
   .....
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
   ...

```
