### ISSUE TITLE
Cannot import a lot of methods

### ISSUE THREAD

**Issue by horvathcsabalaszlo** [akshaaatt/Google-IAP#135]
Hi,

I'm a beginner developer, and need to update my apps to the lastest BillingClient. 
I would use your library, as this seems to be the easiest way and it seems well built.

However, i try to build a sample app to see how it's working, based on your Java example, but  i get a lot of issues.

For this : 
     iapConnector.addBillingClientConnectionListener((status, billingResponseCode) -> {
        Log.d("JSA", "This is the status: "+status+" and response code is: "+billingResponseCode);
        isBillingClientConnected.setValue(status);
    });
i get that Android studio cannot resolve the symbol and for may other methods also. 

In my imports, there is 
import com.limurse.iap.IapConnector;
defined. I wonder what else would be needed? 

Thanks for any help,

**Comment by akshaaatt** [comment]
@horvathcsabalaszlo Update your Android Studio to latest one and use JavaVersion.VERSION_17 as this library uses it

**Comment by horvathcsabalaszlo** [comment]
Hi,

Thanks! :)
