### ISSUE TITLE
Call the onProductsPurchased event even if the user hasn't bought anything

### ISSUE THREAD

**Issue by vitalii-vov** [akshaaatt/Google-IAP#15]
Sorry for my english.
My task is to check if the user has bought the product.

My idea is to request all the purchases made, and if there is no desired purchase in the list, then assume that the user did not make it.
But, after calling getAllPurchases, onProductsPurchased is not called.
I was expecting to get an empty list.

Please make it possible to receive an empty list.
As an option, add the check function IapConnector.isSubscribed(sku);

I wrote code like this:
```java
@Override
protected void onCreate(Bundle savedInstanceState) {
        mIapConnector = new IapConnector(this, InAppConstants.LICENSE_KEY)
                .setSubscriptionIds(InAppConstants.getSubscriptionsList());
        mIapConnector.setOnInAppEventsListener(new InAppEventsListener() {
            @Override
            public void onSubscriptionsFetched(List<DataWrappers.SkuInfo> list) {
               //   after IapConnector loading I need check if user subscription
               //   I call getAllPurchases to show user purchases
               mIapConnector.getAllPurchases();
            }

            @Override
            public void onProductsPurchased(List<DataWrappers.PurchaseInfo> list) {
               //   not called if there are no purchases
               boolean subscribedPremium = list.stream().anyMatch(a -> a.getSku().equals(InAppConstants.SKU_SUBSCRIBE_PREMIUM_ONE_YEAR));
             
            }
            @Override public void onInAppProductsFetched(List<DataWrappers.SkuInfo> list) { }
            @Override public void onPurchaseAcknowledged(DataWrappers.PurchaseInfo info) {  }
            @Override public void onError(IapConnector iapConnector, DataWrappers.BillingResponse billingResponse) { }
        });
        mIapConnector.connect();
}
```

**Comment by akshaaatt** [comment]
You have a similar issue as #7 . We need to come up with an alternative for this here to avoid the backend server situation. Let's see.

**Comment by vitalii-vov** [comment]
It seems to me that these are different problems.
I don't get NPE.

I can wrap NPE in try catch block
```java
try {
   mIapConnector.getAllPurchases();
} catch (NullPointerException npe){
   // empty
}
```

I'm not good at Kotlin, but it seems to me that the reason is in the implementation of the processPurchases function. onProductsPurchased is not called if the user has not purchased anything. It seems to me that this event should always be called.
If you add an else section, then this should solve the problem

```kotlin
private fun processPurchases(allPurchases: List<Purchase>) {
        if (allPurchases.isNotEmpty()) {
           // you code ...
        } else {
           //   need add this line
           inAppEventsListener?.onProductsPurchased(emptyList())
        }
    }
```

There is something similar in one of the forks of the project https://github.com/andj207/Google-IAP/blob/master/iap/src/main/java/com/alphelios/iap/IapConnector.kt

**Comment by akshaaatt** [comment]
@vitalii-vov I meant the use case is the same. I will fix this issue soon. We'll try to incorporate a method to figure whether or not the product has been bought in the current session.

**Comment by akshaaatt** [comment]
Checkout the new implementation in the latest release.
