### ISSUE TITLE
In the latest master MainActivity.kt : 29,,,,,should the yearly Id be subscriptionId?

### ISSUE THREAD

**Issue by JoneJay** [akshaaatt/Google-IAP#23]
MainActivity.kt : 29 ---- .setConsumableInAppIds("base","yearly","quite","moderate", "plenty")

why do not you put the yearly in the setSubscriptionIds?

**Comment by JoneJay** [comment]
And what is the use of games_ids.xml  ??

**Comment by akshaaatt** [comment]
Hey, since there have been issues currently, I have reverted back to the most efficient release so far of 1.0.5. Please make the necessary changes and refer to the code again

**Comment by JoneJay** [comment]
OK......
