### ISSUE TITLE
OnProductRestore

### ISSUE THREAD

**Issue by paktech1** [akshaaatt/Google-IAP#27]
OnProductRestore must be called on once and must give list of own purchases instead of calling it multiple times.

this will allow us to restore purchases on SplashScreen and move to main screen when triggered once.

**Comment by paktech1** [comment]
its been 6 days, no reply, no update, i  had to write my own billing manager and had to stop using this library.

**Comment by akshaaatt** [comment]
You are talking specifically to your own use case of restoring the owned purchases once whereas major use cases can depend upon dynamic processing within the app. I don't see the point of this argument and hence am marking it stale.

**Comment by vitalii-vov** [comment]
The above problem is preferable to multiple calls. A multiple call does not provide an opportunity to process purchases normally.
