### ISSUE TITLE
Issue with Acknowledgment and Payments are getting cancelled

### ISSUE THREAD

**Issue by iNuman** [akshaaatt/Google-IAP#29]
There was a method in your old build to auto acknowledge the purchase which was not working but now in your current build it's not present publicly and purchases are still being canceled as well after some time for not acknowledging.

I think you got a fix lots of things and should update your documentation as well because you had done lots of changes.

<img width="450" alt="Screenshot 2021-04-21 170833" src="https://user-images.githubusercontent.com/25281036/115551308-4b90c280-a2c4-11eb-8d2a-c1c1565e5ba5.png">

**Comment by akshaaatt** [comment]
I have cross checked and verified that there shouldn't be any issue if you are using the latest release of the library. I have been using the library in my own apps for over a week now in production and haven't faced any rejection. Please verify what you are talking about.

**Comment by iNuman** [comment]
It works fine with real payments but for test payments it's returning
payment cancel I tried all possible ways end up implementing payment
manually.
