### ISSUE TITLE
About onPricesUpdated

### ISSUE THREAD

**Issue by JoneJay** [akshaaatt/Google-IAP#30]
1、Why named as prices updated?but actually it's not like $1 to $2, I think it should be named as onPricesFetched
2、The method onPricesUpdated is called 3 times when the view created.
3、The old interface onInAppProductsFetched and onInAppProductsFetched's param : skuDetailsList should be needed, not only the price.For example : description.

**Comment by akshaaatt** [comment]
Changes have been made regarding this and the latest versions support more enhanced usage. Regarding the naming, there is a reason behind it and we wouldn't be making changes to it.

Thank you!
