### ISSUE TITLE
Purchased Item not consumed immediately

### ISSUE THREAD

**Issue by leuroz** [akshaaatt/Google-IAP#31]
Whenever I purchase an item that is part of the consumable keys list, it is not beein processed correctly. onProductPurchased is not beeing called until I try to buy the item again. The Google Play Dialog then says "Product already owned" and in this exact second onProductPurchased is beeing called and the item previously purchased is consumed, so that I can buy it again.
I really hope this can be fixed.

**Comment by akshaaatt** [comment]
Can you please update to the latest version of the library and confirm whether this issue is still present or not?

**Comment by leuroz** [comment]
Thanks but I can't import the Classes with the newest version. 
The Gradle Sync is successull, but after I type "import com.limerse.iap." IapConnector, DataWrappers and so on won't appear.

**Comment by akshaaatt** [comment]
Hi! To test this I added the library to a new project and it all works for me :)
I think you can try and "Invalidate Caches and Restart" on Android Studio in case this cannot be resolved. Other than that please check that you are following the correct and updated docs from the README.

Thanks!

**Comment by leuroz** [comment]
Thanks for your help! I had to update to the newest Android Studio Version and now it works. 
Sadly when I purchase an item from the consumable list, onProductPurchased is still not beein called until I try to buy the item again.

**Comment by akshaaatt** [comment]
Thanks for letting me know @leuroz ! Tbh the version 1.1.7 is yet to be tested by me since my developer console is down but previously I had be using version 1.1.5 myself without any problem. So you can try that out in case you're in a hurry.

Happy Coding! :)

**Comment by kzlsnn** [comment]
Hello, I was having the same problem. Solution: Download the library and include it in the project first, then in the BillingService class.
`when (billingResult.responseCode) {
                                        BillingClient.BillingResponseCode.OK -> {
                                            productOwned(skuDetails, purchase, false)
                                        }
                                        else -> {
                                            Log.d(TAG, "Handling consumables : Error during consumption attempt -> ${billingResult.debugMessage}")
                                        }
                                    }` (From line 164 to 171)

Replace the part with `productOwned(skuDetails, purchase, false)` 

I hope I have helped. Happy Coding!

**Comment by akshaaatt** [comment]
Closing this issue.
