### ISSUE TITLE
Can we have the sample code in java as well?

### ISSUE THREAD

**Issue by shravanvinu** [akshaaatt/Google-IAP#32]
Thanks for the hard work put on this.. 
its really helpful for many people if the sample implementation is done in java too as people looks for library like this are old school developers and not professionals. (like me :))
Many people are using anjlib, as there is no update from them on billing lib 3,  people looking for alternative. this library really has potential.. Also try to ad some keywords in the title all description like billing library 3 , in-app purchase , subscription etc. etc. so that It will be easy to find the library.

**Comment by akshaaatt** [comment]
I've added a JavaSampleActivivity to the codebase. You can check it out @shravanvinu :)

**Comment by shravanvinu** [comment]
Thanks a lot. :)
