### ISSUE TITLE
D/GoogleBillingService: buy. Google billing service is not ready yet.

### ISSUE THREAD

**Issue by GGJdevelope** [akshaaatt/Google-IAP#37]
D/GoogleBillingService: onBillingSetupFinishedOkay: billingResult: com.android.billingclient.api.BillingResult@6b9a8a
I think connection is ok

D/GoogleBillingService: buy. Google billing service is not ready yet.
But purchase window doesnt pop up! what is the problem?

**Comment by GGJdevelope** [comment]
```
List<String> nonConsumablesList = Collections.singletonList(null);
List<String> consumablesList = Arrays.asList("A", "B", "C", "D");
List<String> subsList = Collections.singletonList(null);
 iapConnector=new IapConnector(MainActivity.this,nonConsumablesList,consumablesList,subsList,lises,true);
add listener
use purchase
```

**Comment by akshaaatt** [comment]
Hi @GGJdevelope ! Tbh I am yet to test version 1.1.7 myself on an actual app. This issue will only be resolved from my side in a day or two. If things are urgent for you, I suggest you try to use an older version.

Happy Coding! :)

**Comment by GGJdevelope** [comment]
@akshaaatt Oh~ Thank you for your contribution!

**Comment by akshaaatt** [comment]
You can try version 1.1.5 for now and I am sure it will work. I will test the latest as soon as my developer account is up again and get back to you on the latest.
Thanks!

**Comment by GGJdevelope** [comment]
@akshaaatt  I need purchase info so I will wait your update! 👍

**Comment by GGJdevelope** [comment]
@akshaaatt 1.1.5 throw err 
<img width="1791" alt="스크린샷 2021-06-01 오후 5 07 43" src="https://user-images.githubusercontent.com/57247934/120289182-fd77d180-c2fb-11eb-9820-963c831209c8.png">

and 1.1.4 works until purchase process but purchase listener doesnt work

**Comment by GGJdevelope** [comment]
@akshaaatt I suggest implement 1.1.4's purchase process to 1.1.7

**Comment by akshaaatt** [comment]
Hi @GGJdevelope I personally use 1.1.5 in all my apps without a problem. I think you can try to Invalide Caches and Restart to test that. Other than that I assure you once my developer account is back we'll fix everything because according to me all the logic and everything works fine just need to trim on any unwanted bugs.

**Comment by chocotacos** [comment]
Hey, @akshaaatt I am having the same issue I am using the latest 1.2.2 but the issue is payment dialog is not popping up. Although it's just with my account I am using my friends account & the popup dialog is showing can you help me with that?

**Comment by akshaaatt** [comment]
> Hey, @akshaaatt I am having the same issue I am using the latest 1.2.2 but the issue is payment dialog is not popping up. Although it's just with my account I am using my friends account & the popup dialog is showing can you help me with that?

The latest version is 1.4.2

**Comment by chocotacos** [comment]
Ohh okay, my mistake. The 1.4.2 is causing some errors. Can you help me with that? please!
![Capture](https://github.com/akshaaatt/Google-IAP/assets/55656013/852543b4-e641-4360-841c-d96a6d1f62fe)

**Comment by akshaaatt** [comment]
> Ohh okay, my mistake. The 1.4.2 is causing some errors. Can you help me with that? please!
> 
> ![Capture](https://github.com/akshaaatt/Google-IAP/assets/55656013/852543b4-e641-4360-841c-d96a6d1f62fe) 
> 
> 
> 
> 

The package name was updated recently. Please remove those imports and reimport. That should fix it.
