### ISSUE TITLE
What is consumable and nonConsumable Keys?

### ISSUE THREAD

**Issue by jmimohsin** [akshaaatt/Google-IAP#40]
Hi,

I have product purchase key(example "1") then what should be the value of these Lists:-

```java
List<String> nonConsumablesList = Collections.singletonList("lifetime");
        List<String> consumablesList = Arrays.asList("base", "moderate", "quite", "plenty", "yearly");
        List<String> subsList = Collections.singletonList("subscription");
```

How can I define that?

**Comment by akshaaatt** [comment]
Consumables are those which you want to consume multiple times. Ex: Coins in a game.
Non Consumables are those which you want to be consumed only once. Ex: Removing Ads from an app for premium version.

The product id which you get from the play developer console when you register this in app product of yours is what you enter in this list. Ex: "base","1". etc.

**Comment by jmimohsin** [comment]
If I have only one purchase key then other will be null or something else?

**Comment by akshaaatt** [comment]
Yup!
