### ISSUE TITLE
How to get transaction details?

### ISSUE THREAD

**Issue by jmimohsin** [akshaaatt/Google-IAP#41]
Hi, 

I want to get transaction details like what I have purchased earlier like this:-

```java
TransactionDetails transactionDetails = bp.getPurchaseTransactionDetails("1");
if (transactionDetails != null){
    prefManager.setString("orderId", transactionDetails.purchaseInfo.purchaseData.orderId);
}
```

I want to know that I have already purchased that product or not?

**Comment by jmimohsin** [comment]
I want to know that I have already purchased that product or not?

**Comment by akshaaatt** [comment]
Interesting asks @jmimohsin ! I'll have to add these features. Tbh I think we should add these soon. Let's see if I can find some time to work on adding these :)

**Comment by jmimohsin** [comment]
@akshaaatt plz add it asap if possible otherwise I need to switch to main library.

**Comment by akshaaatt** [comment]
@jmimohsin Cool I'm free today. On it.

**Comment by jmimohsin** [comment]
That's great and I have 1M+ downloads on my app and looking for the stable library before Google deadline.

**Comment by akshaaatt** [comment]
Hi @jmimohsin you had me confused at first! I thought you wanted to know the transaction details of the IAP. However, you only want to know whether the product has already been purchased or not, so you only need to depend on the callback from onProductsRestored() from my library.

**Comment by akshaaatt** [comment]
I provide you with the purchaseInfo which basically gets you all the details you would require from the transaction. For your use case, you only need to check the onProductsRestored() callback.

**Comment by akshaaatt** [comment]
> That's great and I have 1M+ downloads on my app and looking for the stable library before Google deadline.

Would you be interested to add your app's link to this repository's README showcasing which apps use this library?

**Comment by jmimohsin** [comment]
I need to check it today that after initializing iapConnector with product key then onProductRestored automatically call with product details like order id.

Here is the app link :- https://play.google.com/store/apps/details?id=daily.status.earn.money

Yes you can add it. 👍

**Comment by jmimohsin** [comment]
Thanks it's working.
