### ISSUE TITLE
iapConnector?.purchase does not working

### ISSUE THREAD

**Issue by quannh270593** [akshaaatt/Google-IAP#42]
Hi bro!! Please help me!!! iapConnector?.purchase(this@MainActivity, product_id_key) doesn't show anything. My project is waiting review version testing, I filled in the correct input permission license key and product_id. Please explain is it a bug or is it because the app is not published yet so it doesn't show anything??

**Comment by akshaaatt** [comment]
Have you added the product_id_key to the Developer Console under In-App Products?

**Comment by quannh270593** [comment]
yes, i already added them, but onPricesUpdated still returns the empty list, and when i click buy, it doesn't happen anything. i waiting it published in store and check it work, if it not working i have to update app (i don't want to update app)

**Comment by quannh270593** [comment]
i used Google IAP newest version(1.1.7)

**Comment by akshaaatt** [comment]
```kotlin
 iapConnector.addPurchaseListener(object : PurchaseServiceListener {
            override fun onPricesUpdated(iapKeyPrices: Map<String, String>) {
                // list of available products will be received here, so you can update UI with prices if needed
            }

            override fun onProductPurchased(purchaseInfo: DataWrappers.PurchaseInfo) {
               // will be triggered whenever purchase succeeded
            }

            override fun onProductRestored(purchaseInfo: DataWrappers.PurchaseInfo) {
                // will be triggered fetching owned products using IapConnector
            }
        })
```
The onProductPurchased() callback will be triggered once iapConnector.purchase() function is called successfully. I reckon you are not receiving anything yet because your app has not been published yet.
