### ISSUE TITLE
Restore purchase 

### ISSUE THREAD

**Issue by DineshNeupane** [akshaaatt/Google-IAP#43]
Anyway to define restore purchase?

**Comment by truedem** [comment]
And subscription, please.

Two weeks ago the author commented on Reddit how they can add it if there will be some demand.

https://www.reddit.com/r/androiddev/comments/nq6pdf/anyone_know_of_a_non_convoluted_way_to_impliment/h0a6ouq/

**Comment by DineshNeupane** [comment]
managed to sole it by onPurchaseRestored() method. Thanks.
