### ISSUE TITLE
Google auto refund all orders after 3 days

### ISSUE THREAD

**Issue by JVeverGiveUp** [akshaaatt/Google-IAP#44]
I recently integrated your library to my app. I follow your guide, but after 3 days. Google auto refunded all of user's orders (All are non comsumable items). Anything I need to add?
Thanks for your respond.
Details of integration as below:
**1. Add dependency library:**
 _implementation 'com.github.akshaaatt:Google-IAP:1.1.7'_
**2. In the main code:**
String key = "";
        List<String> nonConsumablesList = Arrays.asList("item_1", "item_2", "item_3");
        List<String> consumablesList = Collections.emptyList();
        List<String> subsList = Collections.emptyList();

        iapConnector = new IapConnector(
                this,
                nonConsumablesList,
                consumablesList,
                subsList,
                key,
                true
        );
        iapConnector.addPurchaseListener(new PurchaseServiceListener() {
            public void onPricesUpdated(Map iapKeyPrices) {

            }

            public void onProductPurchased(DataWrappers.PurchaseInfo purchaseInfo) {
                if (purchaseInfo.getSku().equals("item_1")) {
                    //enable feature of item_1
                }
                else if (purchaseInfo.getSku().equals("item_2")) {
                    //enable feature of item_2
                }
                else if (purchaseInfo.getSku().equals("item_3")) {
                     //enable feature of item_3
                }
            }

            public void onProductRestored(DataWrappers.PurchaseInfo purchaseInfo) {

            }
        });

**Comment by JVeverGiveUp** [comment]
Okay, I found solution for this. This is because you said the KEY is optional but it is critical need. Check logic code, if the KEY is missed, it will skip all acknowledge function call. So you will be refunded!

**Comment by akshaaatt** [comment]
Hey, I just had a look at this! The key is essential if you want the product purchased it is mentioned in all the guidelines. It is optional to hardcode here since many prefer to call it through their backend. Otherwise, it is mandatory for successful usage!
