### ISSUE TITLE
error: buy. Google billing service is not ready yet.

### ISSUE THREAD

**Issue by jooy2** [akshaaatt/Google-IAP#46]
I followed the java example in the documentation using version 1.1.7.

The problem is that when I call iapConnector.purchase(), nothing happens.
Only one line is printed in logcat: "error: buy. Google billing service is not ready yet."

I have activated Google Play Services on AVD and completed the google account login.
I tested it with a real device too, but it was the same.

License key and product_id are already registered in development console and string.xml.
I couldn't find any clues that could be the problem.

It's probably similar to the following issue. #42 

Thanks.

**Comment by d-schmidt** [comment]
this is a beta lib and not production ready.

your error could mean many things: SKU not found, the billing service is not yet connected, the SKUs are not yet loaded

**Comment by jooy2** [comment]
I transferred only the billing client based on the SKU I was using before (also an already released app) and proceeded according to the document. The language I used JAVA.

May I know the official support schedule for this library?
Thank you!
