### ISSUE TITLE
How to get purchase token after purchase successfully?

### ISSUE THREAD

**Issue by cellojaan** [akshaaatt/Google-IAP#47]
Hi. I have 2 questions.

1-) How to get Sku price from Google Play?
2-) How to get purchase token after purchase successfully? (I have server-side confirmation)

Thanks.

**Comment by akshaaatt** [comment]
Hi, thanks for bringing this up!

1) Find the price of the sku from `purchaseInfo.skuInfo.price`

2) Try using `purchaseInfo.purchaseToken`

Happy Coding! :)

**Comment by cellojaan** [comment]
Can you give me a example please about purchaseInfo.skuInfo.price? ^_^ @akshaaatt

**Comment by akshaaatt** [comment]
Sure @cellojaan! If you want the sku price after the purchase has been made, you can find it using the above method in the onProductPurchased/onProductRestored callback.

However, if you want it pre-purchase, we'll have to make some changes to the library.
