### ISSUE TITLE
Identify when connect to billing service was a success.

### ISSUE THREAD

**Issue by paktech1** [akshaaatt/Google-IAP#48]
Kindly introduce some method to identify when connect to billing service was a success, or  some method to test if billing is available.

**Comment by akshaaatt** [comment]
Could you present a use case for this? I used to provide such methods but abandoned them because the library users expect the library to work and I make sure of it. The IAP just won't open if the connection hasn't been made and these are asynchronous processes.

**Comment by bhavikmehta5491** [comment]
> Could you present a use case for this? I used to provide such methods but abandoned them because the library users expect the library to work and I make sure of it. The IAP just won't open if the connection hasn't been made and these are asynchronous processes.

Your library always throws an exception in the purchase and subscribe both.
` D/GoogleBillingService: buy. Google billing service is not ready yet.`

Please implement a method to at least acknowledge that the library has been initialized

**Comment by d-schmidt** [comment]
@bhavikmehta5491 this lib is still beta. There are more problems than this.

@akshaaatt a use case would be to disable/enable a purchase button and to display the current, local price once it is initialized and ready.

**Comment by HRankit** [comment]
@d-schmidt  that is what I exactly needed. Pull Request #68 makes it happen.
