### ISSUE TITLE
Bug: refunded and removed entitlement IAP appear as purchased

### ISSUE THREAD

**Issue by adrcotfas** [akshaaatt/Google-IAP#5]
I was testing the refund with removing the entitlement which should remove access to the non-consumable IAPs but I see this is not the case.  

```kotlin
iapConnector.setOnInAppEventsListener(object : InAppEventsListener {
            override fun onInAppProductsFetched(skuDetailsList: List<DataWrappers.SkuInfo>) {
                // I see that this will call queryPurchases, processPurchases and then inAppEventsListener.onProductsPurchased
                // so I assumed this is the way to go to restore previous purchases for users re-installing the app 
                iapConnector.getAllPurchases()
            }
            override fun onProductsPurchased(purchases: List<DataWrappers.PurchaseInfo>) {
                // Here, a previous purchased product but refunded still appears in the list (unexpected)
                // For a different account which did not purchase the IAP in the first place, this is not called (expected)
            }
            ...
})
```

**Comment by adrcotfas** [comment]
Nevermind, I assumed it's a problem in this library but actually it's about a flaw in the Billing Library.  

I found a workaround and wrote about it here: https://issuetracker.google.com/issues/73982566#comment62  
You can find a lot of people complaining about this bug on stackoverflow too.    
Feel free to use that code from my fork here. I just need non-consumable IAP for my use case and made some more changes there.

**Comment by akshaaatt** [comment]
Okaayy!
