### ISSUE TITLE
missing empty check for list of purchases

### ISSUE THREAD

**Issue by d-schmidt** [akshaaatt/Google-IAP#51]
https://github.com/akshaaatt/Google-IAP/blob/ad628f4b8d4ce266031f70c8dfa0ab07b6125530/iap/src/main/java/com/limerse/iap/BillingService.kt#L143

this is missing `!isEmpty()` as `queryPurchasesAsync()` doesn't result in null but empty lists.

**Comment by akshaaatt** [comment]
Thanks. Fixed.
