### ISSUE TITLE
stray e.printStackTrace() to stdout

### ISSUE THREAD

**Issue by d-schmidt** [akshaaatt/Google-IAP#53]
https://github.com/akshaaatt/Google-IAP/blob/ad628f4b8d4ce266031f70c8dfa0ab07b6125530/iap/src/main/java/com/limerse/iap/BillingService.kt#L101

**Comment by akshaaatt** [comment]
I shall be using `e..printStackTrace(System.out)` then to fix this issue. Thanks!

**Comment by d-schmidt** [comment]
You never want to print to stdout. Log it like everything else.

**Comment by akshaaatt** [comment]
Makes sense. Done.
