### ISSUE TITLE
How to get Price and Currency Symbol Separately? 

### ISSUE THREAD

**Issue by amarilindra** [akshaaatt/Google-IAP#56]
`onPricesUpdated` send `iapKeyPrices: Map<String, String>` which contains the list of SKUs and their price. 

Currently, the price is a String Eg: Rs. 300.00
Is it possible to get "Rs" (String) and "300.00" (Double) separately? 

**Use case**: We'll be running seasonal discounts and it is important to get the price (Double) to calculate the price difference.

**Comment by akshaaatt** [comment]
Sounds fair @amarilindra I'll try to look into this soon but can't promise a quick fix right now.
