### ISSUE TITLE
Bug: older purchases are not restored

### ISSUE THREAD

**Issue by adrcotfas** [akshaaatt/Google-IAP#59]
I'm testing the library with an app installed on a device where the user has a non-consumable purchase already made in the past.  
This purchase is not restored and `onPurchasesUpdated` never gets called unless I make a new purchase.  
Older versions of the library did not have this issue (previous to the package name change).

**Comment by akshaaatt** [comment]
This should be fixed now. Can you please confirm?

**Comment by adrcotfas** [comment]
I'm not using your library anymore but you can close it.
