### ISSUE TITLE
How to check if the user has an active subscription in Android, Google Play?

### ISSUE THREAD

**Issue by DanielBarcenas97** [akshaaatt/Google-IAP#61]
How to check if the user has an active subscription in Android, Google Play?

**Comment by Emranul-Islam** [comment]
did you find  solution for this problem

**Comment by akshaaatt** [comment]
I personally haven't played much with subscriptions but I could look into this the coming weekend.

**Comment by dhirajved** [comment]
iapConnector.addPurchaseListener(object : PurchaseServiceListener {
                override fun onPricesUpdated(iapKeyPrices: Map<String, DataWrappers.ProductDetails>) {
                  
                }

                override fun onProductPurchased(purchaseInfo: DataWrappers.PurchaseInfo) {
                    Log.e("InAPP", "onProductPurchased: ${purchaseInfo.sku}\n")
                    
                }

                override fun onProductRestored(purchaseInfo: DataWrappers.PurchaseInfo) {
                    Log.e("InAPP", "onProductRestored: ${purchaseInfo.sku}\n")
                   

                }
            })

onProductRestored in this method get active subscription.
