### ISSUE TITLE
How to handle PENDING purchases?

### ISSUE THREAD

**Issue by moisoni97** [akshaaatt/Google-IAP#7]
How can we handle pending purchases?
As far as I understand `iapConnector.getAllPurchases();` will call `onProductsPurchased listener` and there we can check if the purchase was successful or not, but calling `getAllPurchases();` always crash under `NPE`
Is there a way to get the status of the purchase (accepted or declined)?

**Comment by akshaaatt** [comment]
This is something that currently needs to be worked on.

**Comment by akshaaatt** [comment]
The NPE occurs when you call getAllPurchases() when the client is not ready yet since it is an asynchronous process.

**Comment by emzy07** [comment]
PR is on the way :)

**Comment by akshaaatt** [comment]
We still need a fix to this situation. For now we have made the ```getAllPurchases()``` function private and it will be called only once during initialization. @moisoni97 to keep a track of whether or not the purchase was successful, you should update to your backend server whenever the purchase starts and when it is done, and match the results to update your UI/database.

**Comment by Skaldebane** [comment]
Hi there! I came across the same issue here. I want to handle PENDING purchases, but it seems like onProductPurchased never gets called with that state, even when using "Slow test card, approves after few minutes". It only gets called when the purchase goes through.

I have no backend server or anything, but as a matter of good UX I want to warn the user that the transaction is pending without having to start the purchase flow from Google Play.

Thanks in advance!
