### ISSUE TITLE
How can i find expiry time

### ISSUE THREAD

**Issue by Emranul-Islam** [akshaaatt/Google-IAP#71]
I want to know when my subscription time will expire is there any way in this library ??

**Comment by chnouman** [comment]
@Emranul-Islam have you figured out anything yet?

**Comment by Emranul-Islam** [comment]
@chnouman no i'm looking for it

**Comment by clashcaddie** [comment]
You can calculate the expiry time by getting the `purchaseInfo.purchaseTime`  and adding the `purchaseInfo.skuInfo.skuDetails.subscriptionPeriod`  to it

Subscription Period
- "P1W" is 1 Week
- "P1M" is 1 Month
- "P3M" is 3 Months
- "P6M" is 6 Months
- "P1Y" is 1 Year

**Comment by Emranul-Islam** [comment]
Thanks for help @clashcaddie
